---
title: "Predimiento"
author: "Grace Pratt"
date: "9/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("readxl")
```

##Test 11/09/19

```{r 11/09/19}
path <- "Spreadsheets/11.09.19_registro.xlsx"
sheets <- readxl::excel_sheets(path) #use the readxl package to identify sheet names 
prendimiento <- lapply(sheets, readxl::read_excel, path = path)  #read the data from all 3 sheets into a list
names(prendimiento) <- sheets # give the list of datatables their assigned sheet names

prendimiento
```



```{r}
arboles <- prendimiento$arboles

counts <- arboles %>%
  group_by(proyecto_id)%>%
  count()

buinzoo <- arboles %>% filter(proyecto_id == "Buinzoo_Buin")

buinzoo_numbers <- buinzoo %>% 
  select(vivos, muertos, bueno, regular, malo, seco, comido)  %>% 
  summarise_all(sum, na.rm = TRUE)

tidy_format <- gather(buinzoo_numbers, key = "type", value = "count")

ggplot(data= tidy_format, aes(x=type, y=count)) +
  geom_bar(stat = "identity")
```



```{r}
summary <- arboles %>% 
  select(proyecto_id, vivos, muertos, bueno, regular, malo, seco, comido)%>%
  group_by(proyecto_id) %>%
  summarise_all(sum, na.rm = TRUE)%>%
  left_join(prendimiento$proyectos) %>%
  select(proyecto_id, vivos, muertos, bueno, regular, malo, seco, comido, arboles_plantados, arboles_muestreo) %>%
  mutate(prendimiento = vivos/arboles_plantados)

summary 
```


```{r}
ggplot(data= summary, aes(x=proyecto_id, y=prendimiento)) +
  geom_bar(stat = "identity")

```




```{r}
arboles %>%
  group_by(proyecto_id, especie)%>%
  summarise(total_vivos = sum(vivos, na.rm=TRUE))

```














